<div id="menu-frame">
    <?php $this->InitMainMenu(); ?>
</div>
<div id="content-wrapper">
    <div id="vert-nav">
        <?php $this->InitVertMenu(); ?>
<!--        <ul class="top-level">
            <li><a href="#"><i class="icon-doc"></i>Новый</a></li>
            <li><a href="#"><i class="icon-list"></i>Текущие<em>+2</em></a></li>
            <li><a href="#"><i class="icon-folder"></i>Архив</a></li>
            <li><a href="#"><i class="icon-help"></i>Справка</a></li>
        </ul> -->
    </div>
    <div id="error-frame">
    </div>
    <div id="status-frame">
    </div>
    <div id="content-frame">
    </div>
</div>
<div id="debug-frame">
</div>
