        <nav>
            <ul class="clearfix">
                <li class="rootmenu"><a href="#">Home</a></li>
                <li class="rootmenu"><a href="#">WordPress</a>
                <!-- First Tier Drop Down -->
                <ul>
                    <li><a href="#">Themes</a></li>
                    <li><a href="#">Plugins</a></li>
                    <li><a href="#">Tutorials</a></li>
                </ul>        
                </li>
                <li class="rootmenu"><a href="#">Web Design<span>&#9662</span></a>
                <!-- First Tier Drop Down -->
                <ul>
                    <li><a href="#">Resources</a></li>
                    <li><a href="#">Links</a></li>
                    <li><a href="#">Tutorials<span>&#9656</span></a>
                    <!-- Second Tier Drop Down -->
                    <ul>
                        <li><a href="#">HTML/CSS</a></li>
                        <li><a href="#">jQuery</a></li>
                        <li><a href="#">Other</a>
                            <!-- Third Tier Drop Down -->
                            <ul>
                                <li><a href="#">Stuff</a></li>
                                <li><a href="#">Things</a></li>
                                <li><a href="#">Other Stuff</a></li>
                            </ul>
                        </li>
                    </ul>
                    </li>
                </ul>
                </li>
                <li class="rootmenu"><a href="#">Graphic Design</a></li>
                <li class="rootmenu"><a href="#">Inspiration</a></li>
                <li class="rootmenu"><a href="#">Contact</a></li>
                <li class="rootmenu"><a href="#">About</a></li>
            </ul>
        </nav>
