<nav>
    <ul class="clearfix">
        <li class="rootmenu"><a href="#"><i class="icon-home"></i>&nbsp;Главная</a></li>
        <li class="rootmenu"><a href="#"><i class="icon-truck"></i>&nbsp;Заказы&#9662</a>
            <ul>
                <li><a href="#"><i class="icon-doc"></i>&nbsp;Новый...</a></li>
                <li><a href="#"><i class="icon-list"></i>&nbsp;Текущие</a></li>
                <li><a href="#"><i class="icon-folder"></i>&nbsp;Архив</a></li>
            </ul>        
        </li>
        <li class="rootmenu"><a href="#"><i class="icon-money"></i>&nbsp;Цены</a></li>
        <li class="rootmenu"><a href="#"><i class="icon-cog"></i>&nbsp;Инструменты&#9662</a></li>
        <li class="rootmenu"><a href="#"><i class="icon-help"></i>&nbsp;Справка</a></li>
        <li class="rootmenu"><a href="#"><i class="icon-user"></i>&nbsp;Профиль</a></li>
    </ul>
</nav>