<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <link type="text/css" href="css/style.css" rel="stylesheet" media="screen" charset="utf-8" />
        <link type="text/css" href="css/fontello.css" rel="stylesheet" media="screen" charset="utf-8" />
        <link type="text/css" href="css/jquery-ui.css" rel="stylesheet" />
        <title>Knauf Order Desk</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Style-Type" content="text/css" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <meta name="author" content="Firsov Alexander" />
        <script type="text/javascript" src="js/jquery-1.11.2.min.js"></script>
        <script type="text/javascript" src="js/jquery-ui.min.js"></script>
        <script type="text/javascript" src="js/ajax.js"></script>
    </head>
    <body>
        <div id="page-wrapper">
            <div id="top-frame">
                <img src="./img/logo.gif" align="top"/>
                <img src="./img/logo.png" align="top"/>
            </div>
            <div id="loader-block" style="display: none;">
            </div>
            <div id="main-frame">
                <?php $this->SendMainFrame(); ?>
            </div>
            <div id="debug-frame">
                <?php $this->Debug();?>
            </div>
        </div>
<!--        <script>
            $(document).ready(function(){
                $("#loader").show();
                $("#main-frame").load("/Application/Content",function(){$("#loader").hide();});			
          });
	</script> -->
    </body>
</html>