---
routes:
    Index: {controller: IndexController , default: yes}
    Install: {controller: InstallController}

classmap:
    IndexController : IndexController.php
    InstallController : InstallController.php