---
Routes:
    Index: {controller: IndexController , default: yes}
    Install: {controller: InstallController}

Controllers:
    IndexController : IndexController.php
    Controller1 : Controller1.php

Views:
    MainView: MainView.phtml
    ContentView: ContentView.phtml
    NavView: NavView.phtml