---
routes:
    Index: {controller: IndexController , default: yes}
    Install: {controller: InstallController}

classmap:
    IndexController : IndexController.php
    Controller1 : Controller1.php
    