---
Routes:
    Index: {controller: IndexController , default: yes}
    Install: {controller: InstallController}
    Content: {controller: ContentController}
Controllers:
    IndexController : IndexController.php
    InstallController : InstallController.php
    ContentController: ContentController.php
Views:
    MainView: MainView.phtml
    ContentView: ContentView.phtml
    InstallView: InstallView.phtml
    NavView: NavView.phtml
