---
Routes:
    Index: {controller: IndexController , default: yes}
    Install: {controller: InstallController}
    Content: {controller: ContentController}
Controllers:
    IndexController : IndexController.php
    InstallController : InstallController.php
    ContentController: ContentController.php
Views:
    Template: TemplateView.phtml
    MainFrame: MainFrameView.phtml
    ErrorView: ErrorView.phtml
    InstallView: InstallView.phtml